# Generated by Django 3.2.7 on 2021-09-25 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=64)),
                ('quantity_in_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_id', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('from_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='inventory_management.location')),
                ('to_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='inventory_management.location')),
            ],
        ),
    ]
