# Generated by Django 3.2.7 on 2021-09-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmovement',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
