# Generated by Django 3.2.7 on 2021-09-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_alter_productmovement_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmovement',
            name='product',
            field=models.ForeignKey(default='aaaa', on_delete=django.db.models.deletion.CASCADE, to='inventory_management.product'),
            preserve_default=False,
        ),
    ]
